export const CREATE_THINGS = "THINGS/CREATE_THINGS";
export const THING_ATTACHED = "THINGS/THING_ATTACHED";
export const THING_DETACHED = "THINGS/THING_DETACHED";
export const THING_ACTIVATED = "THINGS/THING_ACTIVATED";
export const DEACTIVATE_THING = "THINGS/DEACTIVATE_THING";
export const THING_DEACTIVATED = "THINGS/THING_DEACTIVATED";
export const HANDLE_THING_ACTION = "THINGS/HANDLE_THING_ACTION";
