export const CONNECT = "MQTT/CONNECT";
export const CONNECTED = "MQTT/CONNECTED";
export const RECONNECTING = "MQTT/RECONNECTING";
export const RECONNECTED = "MQTT/RECONNECTED";
export const DISCONNECT = "MQTT/DISCONNECT";

export const SUBSCRIBE = "MQTT/SUBSCRIBE";
export const UNSUBSCRIBE = "MQTT/UNSUBSCRIBE";
export const MESSAGE_ARRIVED = "MQTT/MESSAGE_ARRIVED";
export const MESSAGE_PUBLISHED = "MQTT/MESSAGE_PUBLISHED";

export const CONFIG_CHANGED = "MQTT/CONFIG_CHANGED";
